name: "Show Status of Obsino"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  project-status:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Status Text
        run: |
          nix run .#status 2>/dev/null | sed 's/\x1b\[[0-9;]*m//g' >> status_output.txt

      - name: Render Codesnap Figure
        run: |
          mkdir -p assets
          cargo install codesnap-cli
          codesnap -f status_output.txt \
            --code-font-family "Cascadia Code" \
            --output ./assets/status.png

      - name: Deploy Figure to Github Page Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./assets
          publish_branch: gh-pages
          keep_files: false
